language: node_js
node_js:
- '0.12'
branches:
  only:
  - master

notifications:
  email:
    recipients:
    - raymondjohnhill@gmail.com
    on_success: change
    on_failure: always
  slack: thecomfyseat:jVMGoJuVUS90mBAB6Ogw1jAq
